# LaCAM settings
map_file        = "./assets/string.map"
scen_file       = "./assets/string.scen"
num_agents      = 5
verbose         = 1
seed            = 1
time_limit_ms   = 5000
flg_star        = false
training_mode   = "best"

# RL training settings
epochs          = 100
lr              = 1e-3
device          = "auto"
output_dir      = "./output/string/run1"
seed_training   = 1
